In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('reduced_project_info.csv')
data

,Unnamed: 0,processDate,rating,finished,title,language,words,hits,kudos,comments,bookmarks,date,restricted
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,1,2020-07-29 21:35:52,1.0,1.0,Analysis of the Obvious,1.0,2751.0,9643.0,43.0,1.0,3.0,2008-09-13,0
2,2,2020-07-29 21:38:01,1.0,1.0,Dense Like Chocolate Cake,1.0,4127.0,11831.0,24.0,73.0,6.0,2008-09-13,0
3,3,2020-07-29 21:38:01,2.0,1.0,Dedication,1.0,5836.0,15812.0,25.0,57.0,6.0,2008-09-13,0
4,4,2020-07-29 21:38:01,2.0,1.0,Dedication,1.0,5836.0,4803.0,51.0,65.0,13.0,2008-09-13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,2020-07-30 00:13:46,-1.0,1.0,"Finally, Freedom",1.0,2775.0,1561.0,180.0,8.0,18.0,2014-05-28,0
999996,999996,2020-07-30 00:02:11,1.0,1.0,Let's Not Tell Dad About This,1.0,790.0,913.0,41.0,3.0,1.0,2014-05-04,0
999997,999997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
999998,999998,2020-07-30 00:15:37,1.0,1.0,Moira's Thoughts,1.0,654.0,158.0,2.0,0.0,0.0,2014-05-04,0
999999,999999,2020-07-30 00:21:46,-1.0,1.0,Forgotten Dreams,1.0,1935.0,2232.0,47.0,0.0,6.0,2014-05-04,0